---
device: multi
input_channel: 6
obsv_len: 5
out_layer: poselu
pred_len: 20
---
batch_size: 20
checkpoint_dir: model/scud_poselu_enll
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
dataset_label_path: data/single_crossing_uniform_dataset/test/all_data.csv
dataset_name: single_crossing_uniform_dataset
dataset_path: data/single_crossing_uniform_dataset/test
model_path: model/scud_poselu_enll
